version: "2"

services:
  frontend:
    container_name: "react_app"
    build: docker_images
    environment:
      env_file: .env
      NODE_ENV: development
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app